#cloud-config
package_update: true
package_upgrade: true

users:
  - name: ${user_admin_name}
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    passwd: ${user_admin_password}
    sudo: ALL=(ALL) ALL
    ssh-authorized-keys:
      - ${user_admin_ssh_key}

  - name: ${user_mantainer_name}
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    ssh-authorized-keys:
      - ${user_mantainer_ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/ssh/sshd_config.d/hardening.conf
    content: |
      Port ${ssh_port}
      PermitRootLogin no
      PasswordAuthentication no
      PubkeyAuthentication yes
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      X11Forwarding no
      AllowAgentForwarding no
      MaxAuthTries 3
      ClientAliveInterval 300
      ClientAliveCountMax 2
      LoginGraceTime 120
      Protocol 2
      AllowUsers ${user_admin_name} ${user_mantainer_name}

packages:
  - fail2ban

runcmd:
  # Fail2ban for SSH
  - echo -e "[sshd]\nenabled = true\nport = ${ssh_port}\nfilter = sshd\nlogpath = /var/log/auth.log\nmaxretry = 5\nfindtime = 300\nbantime = 120" > /etc/fail2ban/jail.d/sshd.local
  - systemctl restart fail2ban
  - curl -fsSL https://tailscale.com/install.sh | sh
