---
- name: Server Hardening Playbook
  hosts: all
  become: true
  vars_files:
    - secret-vars.yml

  tasks:
    - name: Include package installation tasks
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Include user creation tasks
      ansible.builtin.include_tasks: tasks/users.yml

    - name: Include SSH hardening tasks
      ansible.builtin.include_tasks: tasks/ssh_hardening.yml

    - name: Include Tailscale setup
      ansible.builtin.include_tasks: tasks/tailscale.yml

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Restart Fail2Ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
